### PR TITLE
Txpool refactoring: Replace added/adding attributes of SubPool

### PR DESCRIPTION
**Pull request by jomuel**

### CODE REVIEW

**Comment by jomuel** [comment]
@AlexeyAkhunov I verified in devnet tx promotion still works, think we can merge this then.

**Comment by AskAlexSharov** [comment]
@jomuel hi. some people see much of this logs now: 
```
WARN[04-06|23:37:29.671] [txpool] flush: sender address not found by ID
```
not sure is it related to this PR or not

**Comment by jomuel** [comment]
> @jomuel hi. some people see much of this logs now:
> 
> ```
> WARN[04-06|23:37:29.671] [txpool] flush: sender address not found by ID
> ```
> 
> not sure is it related to this PR or not

Will check later

**Comment by jomuel** [comment]
As far as I could tell it is not related to this PR, but I could not find another cause either. I'll figure out what to do about it.

**Pull request merged**
