### PR TITLE
[wip] compression based on deflate specification

### PR DESCRIPTION
**Pull request by racytech**
it takes less disk space for the same inputs, it also takes less time to handle compression of many inputs with different sizes (~1GB of total words tested), but requires a bit more time to iterate(fetch) over words in compressed file (test benchmarks) . The idea is fully taken from https://www.w3.org/Graphics/PNG/RFC-1951, except couple of things that are not included in this compression yet, such as compression with fixed Huffman tree.

### CODE REVIEW

**Comment by AskAlexSharov** [comment]
Thank you!
Please merge `main` into this branch

here are bench results 
```
pkg: github.com/ledgerwatch/erigon-lib/ccompress
cpu: AMD Ryzen 9 3900X 12-Core Processor
BenchmarkDecompressNext-24           	 3553144	       339.7 ns/op	      20 B/op	       2 allocs/op
BenchmarkDecompressSkip-24           	 3772425	       306.1 ns/op	      20 B/op	       2 allocs/op
BenchmarkDecompressMatch-24          	 9537154	       117.9 ns/op	      25 B/op	       2 allocs/op
BenchmarkDecompressMatchPrefix-24    	 9236774	       125.9 ns/op	      25 B/op	       2 allocs/op

pkg: github.com/ledgerwatch/erigon-lib/compress
cpu: AMD Ryzen 9 3900X 12-Core Processor
BenchmarkDecompressNext-24           	11367271	        89.84 ns/op	      16 B/op	       1 allocs/op
BenchmarkDecompressSkip-24           	55349064	        23.23 ns/op	       0 B/op	       0 allocs/op
BenchmarkDecompressMatch-24          	66469296	        16.72 ns/op	       0 B/op	       0 allocs/op
BenchmarkDecompressMatchPrefix-24    	35117092	        36.56 ns/op	       0 B/op	       0 allocs/op
```

Let's take a look - why 2 allocs are happening in `ccompress`, maybe can fix. 

For Erigon compression speed is not important, but decompression is important - because we do compress files once but read/decompress on every RPC call. Compression ratio is useful too. How much data will it read/decompress if we try to read value of 10bytes size? (Where is this place in code?)

**Comment by racytech** [comment]
Thanks Alex!

Great feedback, I know exactly what is required from compressor/decompressor. This version isn't complete version. I'll change it and make it satisfy core requirements.

1. Should I cancel current PR and create new one?

2. Yeah, it takes bit more time to unpack bits and restore original bytes, so the iteration is slower. And allocations can be fixed, I'll take a look at the code and see why is this happening.  

3. Right now to if we need to read 10 bytes word from compressed file, decompressor will decompress 3 blocks (if compressed file has more then 3 compressed blocks) which is (65535 * 3) bytes and keeps those blocks in the memory, to make next read faster. Since this compressor compresses bytes based on frequency and repetition, it requires bit packing and unpacking which requires sometime. So to make next reads faster I decided to decode 3 blocks at a time. But it is possible to read/decode 10 bytes exactly.

4. I don't think I understood the question. Right now compressed file is sequence of compressed blocks. Uncompressed block is 64KB in size and may contain multiple words in it or single word may take multiple blocks. If any word doesn't fully fit in a block, part of it stays in a block until block is full and part of it goes to the next block. Right now compressed block doesn't have integral number of bytes (end of one block and start of new block may share the same byte in compressed file). If it is required to index each word like in array (e.g Decompressor.get_word(num_word) or Decompressor.go_to(num_word)) it is also possible to do.

5. I have goerli snapshots and tested on transactions snapshot. I'll will ask it anyway.

**Comment by AskAlexSharov** [comment]
1. as you feel more comfortable. for me keep current is fine, just mark it as a [wip] or draft, then nobody merge by mistake.

3. `keeps those blocks in the memory, to make next read faste` OS also does keep recently touched pages of MMAP in PageCache - means we double the RAM (but having some limited lru of uncompressed blocks is good idea in general)

4. As simple example see in erigon: `turbo/snapshotsync/block_snapshots.go:HeadersIdx` there we build index on existing segments. This index allow answer 2 queries, let's talk only about 1 now: `select header where block_number=1234`. This index internally has structure like: `word_number -> offset_in_segment` and each segment does has common field base_entity_id where in this case we store min(header_number) in this segment. And to serve above query we do next logic: 
```
offset := idx.Lookup(1234 - seg.base_entity_id)
getter := seg.MakeGetter()
getter.Reset(offset)
foundHeader, _ := seg.Next()
```
 
Internally in index all that offsets encoded by EliasFano encoding, and this encoding can't work with 2 digits per entity (block_number, offset_inside_uncompressed_block).

**Comment by AskAlexSharov** [comment]
let's open new PR when need

**Pull request closed without merging**
