### PR TITLE
Add nodeInfo GRPC methods

### PR DESCRIPTION
**Pull request by dsavelev**
Add GRPC methods required for nodeInfo implementation (https://github.com/ledgerwatch/erigon/issues/2679)

### CODE REVIEW

**Comment by AlexeyAkhunov** [comment]
Thank you! Would you mind making a corresponding PR into `ledgerwatch/interfaces` ? Once that is merged, we can update `git subtree` thing for this PR

**Comment by dsavelev** [comment]
[Done](https://github.com/ledgerwatch/interfaces/pull/84), are there any more steps? I didn't find any docs about the workflow, unfortunately.

**Comment by AlexeyAkhunov** [comment]
Great, you can use this to bring the interfaces change into your PR: https://github.com/ledgerwatch/interfaces#suggested-integration-into-other-repositories (the option with 3 commands)

**Comment by AlexeyAkhunov** [comment]
I mean this:
```
git rm -rf interfaces
git commit -m"Remove interfaces for replacement"
git subtree add --prefix interfaces --squash https://github.com/ledgerwatch/interfaces <tag_or_commit>
```

**Comment by dsavelev** [comment]
Done, thank you.

**Comment by AlexeyAkhunov** [comment]
Ok, now you can use commit `da3c239ed6a13e64a93d1e44e26f2856335bcbfe` to update the PR in Erigon:
``
go get github.com/ledgerwatch/erigon-lib/direct@da3c239ed6a13e64a93d1e44e26f2856335bcbfe
go mod tidy
```

**Pull request merged**
